In [74]:
import numpy as np

In [75]:
n1 =np.arange(10).reshape(2,5)
print(n1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [76]:
np.arange(16).reshape(8,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [77]:
np.arange(16).reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

### stacking:
        - vstack -> we can add rows
        - hstack -> to add columns

In [78]:
a1 = np.random.randint(1,10,(2,1))
print(a1)
b1 = np.random.randint(1,10,(2,1))
print(b1)
print('--vstack---')
print(np.vstack((a1,b1)))
print('----------------')
print(a1)

[[5]
 [6]]
[[9]
 [6]]
--vstack---
[[5]
 [6]
 [9]
 [6]]
----------------
[[5]
 [6]]


In [79]:
# example on hstack:
a2 = np.random.randint(1,10,(2,2))
b2 = np.random.randint(1,10,(2,2))
print('----hstack---------')
print(np.hstack((a2,b2)))

----hstack---------
[[3 9 7 2]
 [7 2 2 8]]


#### ravel() and flatten():
             - To convert the numpy array into n-dimensional to 1-dimensional.

In [80]:
# example on ravel().
a = np.array([[1,2],[3,4]])
print('Original Array...')
print(a)
print('Dimensios is:',a.ndim)
b = a.ravel()
print(b)
print('b dimensions: ',b.ndim)
b[0] = 100
print(b)
print('original a numpy array: ')
print(a)

Original Array...
[[1 2]
 [3 4]]
Dimensios is: 2
[1 2 3 4]
b dimensions:  1
[100   2   3   4]
original a numpy array: 
[[100   2]
 [  3   4]]


In [81]:
# example on flatten():
a1 = np.array([[4,5],[7,8]])
print(a1)
b2 = a1.flatten()
print(b2)
b2[1]=45
print(b2)
print('to print the original array: ')
print(a1)

[[4 5]
 [7 8]]
[4 5 7 8]
[ 4 45  7  8]
to print the original array: 
[[4 5]
 [7 8]]


### Data Analysis and Pandas:

- Pandas Introduction
    - Pandas stands for 'Python Data Analysis Library'.
    - It is open source library.
    - It is Excellent tool for Data processing and Analyzing of real world data.
    
- Pandas has two different data Structures:
- 1. Series Data Structures:
- 2. DataFrame data Structure

- 1. Series Data Structure:
         - It is mainly used for to create the 1-d dimensional with named index..
       
- 2. DataFrame Data Structure:
         - It is mainly used for to create the 2-d dimensional array in the format rows and columns.
         
- Pandas is mainly used for data analysis and data manipulations.
- By using pandas we read the large amount of data like..,excel,csv,tabular..

- 1. How to installing and importing pandas?
- IDLE prefer with pip? pip install pandas
- Importing library: import pandas as pd

### Series Data Structure:
     - Creating Series object using list,tuple,dictionary and also numpy array.
     - Create pandas Series from array-like object using pd.Sries()
     
     - syntax: pd.Series(list,tuple,dict,numpy_array,indexnames)
     
     - The number of elements in the index list is always equal to the number of elements in the specified series.

In [82]:
import pandas as pd

In [83]:
# Creation of series data structure using list?
L1 = [10,20,0]
sd1 = pd.Series(L1)
print(sd1)
print(type(sd1))

0    10
1    20
2     0
dtype: int64
<class 'pandas.core.series.Series'>


In [84]:
# To change the index names..
sd1.index = ['A','B','c']
sd1

A    10
B    20
c     0
dtype: int64

In [85]:
sd2 = pd.Series([23,'python',34.5,89],index=['A','B','C','D'])
print(sd2)

A        23
B    python
C      34.5
D        89
dtype: object


In [86]:
# To create the Series using numpy array?
np1 = np.array([10,20,30])
s2 = pd.Series(np1)
s2

0    10
1    20
2    30
dtype: int32

In [87]:
# Creation of Series using Dictionary?
d1 = {'Name':'Aadyan','Rno':510,'Branch':'CSE'}
sd3 = pd.Series(d1)
print(sd3)

Name      Aadyan
Rno          510
Branch       CSE
dtype: object


In [88]:
# creation of series using tuple:
sd4 = pd.Series((10,20,30))
print(sd4)

0    10
1    20
2    30
dtype: int64


### Series Indexing:
- To get the data from the series..
- To access the values from a series using index names..

In [89]:
sd2 = pd.Series([10,20,30,'apssdc',45.6,'Python'])
print(sd2)

0        10
1        20
2        30
3    apssdc
4      45.6
5    Python
dtype: object


In [90]:
# To access the value from a series..
sd2[2]

30

In [91]:
sd3

Name      Aadyan
Rno          510
Branch       CSE
dtype: object

In [92]:
sd3['Name']

'Aadyan'

In [93]:
sd2[::2] # To get the alternative rows

0      10
2      30
4    45.6
dtype: object

In [94]:
sd2[:3]

0    10
1    20
2    30
dtype: object

In [95]:
sd2[::-1]

5    Python
4      45.6
3    apssdc
2        30
1        20
0        10
dtype: object

In [96]:
sd2[0]

10