#### Data Preprocessing with Scikit learn

#### Preprocessing Techniques

* Data Preprocessing is a technique that is used to convert raw data into a clean dataset

### Data preprocessing steps

* Loading data (reading files)
* Exploring data (Summarizing,statistics etc..)
* Cleaning data (handling missing data)
* Transforming data (Scaling ,feature engineering etc..)
    * will learn data preprocessing technique with scikit-learn,one of the most popular frameworks used for DataScience
    * The scikit-learn library include tools for data preprocessing and data mining.
    * It is imported in python via statement import sklearn
    * providesmachinelearningalgorithms: classification,regression,clustering,model validation etc
    * scikitlearn built on Numpy,Scipy and Matplotlib  

### Data Imputation(used to deal with missing values)

* Data imputation is a method for retaining the majority of dataset's set and information by substituting missing data with a different value.
* If the dataset is missing too many values,we just don't use it.
* if only a few of the values are missing,we can perform data imputation to substitute the missing data with some other values
* There are many different methods for data imputation
     * Using the mean value
     * Using the median value
     * Using the most frequent value(mode)
     * Filling missing values with a constant

#### Data imputation

In [1]:
from sklearn.impute import SimpleImputer

In [2]:
import pandas as pd
import numpy as np
di={
    "a":pd.Series([10,89,76,np.nan,56],index=[1,2,3,4,5]),
    "b":pd.Series([454,34,23,98],index=[1,3,4,5]),
    "c":pd.Series([13,45,35,35],index=[1,2,3,4])
}
df=pd.DataFrame(di)
df

a      b     c
1  10.0  454.0  13.0
2  89.0    NaN  45.0
3  76.0   34.0  35.0
4   NaN   23.0  35.0
5  56.0   98.0   NaN

* fit_transform() from sklearn,preprocessing class is used to preprocessing data for model training
* fit() method calculates various required parameters and
* transform() method applies the calculated parameters to standardize the data
* the fit_transform() is used to fit the data into a model and transform it into a form that is more suitable for model in a single step.This saves our time and effort for calling both fill() and transform() separately

In [3]:
si=SimpleImputer(strategy="median")
si.fit_transform(df)

array([[ 10., 454.,  13.],
       [ 89.,  66.,  45.],
       [ 76.,  34.,  35.],
       [ 66.,  23.,  35.],
       [ 56.,  98.,  35.]])

In [4]:
df.median()

a    66.0
b    66.0
c    35.0
dtype: float64

In [5]:
si=SimpleImputer(strategy="mean")
si.fit_transform(df)

array([[ 10.  , 454.  ,  13.  ],
       [ 89.  , 152.25,  45.  ],
       [ 76.  ,  34.  ,  35.  ],
       [ 57.75,  23.  ,  35.  ],
       [ 56.  ,  98.  ,  32.  ]])

In [6]:
df.mean()

a     57.75
b    152.25
c     32.00
dtype: float64

In [7]:
si=SimpleImputer(strategy="most_frequent")
si.fit_transform(df)

array([[ 10., 454.,  13.],
       [ 89.,  23.,  45.],
       [ 76.,  34.,  35.],
       [ 10.,  23.,  35.],
       [ 56.,  98.,  35.]])

In [8]:
si=SimpleImputer(strategy="constant",fill_value=-1)
si.fit_transform(df)

array([[ 10., 454.,  13.],
       [ 89.,  -1.,  45.],
       [ 76.,  34.,  35.],
       [ -1.,  23.,  35.],
       [ 56.,  98.,  -1.]])

### Task
* Load titanic dataset
* clean data by using simpleimputer

In [ ]:
[10kg ,1000 tones , 70 gms, 800 gms] --- weights

10+100+70+800 --->in correct

* Inorder to do sum of weights we have to convert all units into same unit or unique format,
this is nothing but scaling

### Feature scaling

* Feature scaling is a data preprocessing technique that invloves transforming the values of feature or variablesin a dataset into a similar scale.
* Feature scaling is the process of normalizing the range of features in a dataset
* real world data often contain features that are varying in degrees of magnitude,range and units
* Therefore inorder for machine learning models to interpret these feartures on the same scale,we need to perform feature scaling

### Scaling techniques
* used to convert raw data into meaningful data

* 1.Standardizing Data
* 2.Data Range
* 3.Normalizing Data
* 4.Robust scaling

### 1. Standardizing data(column wise or label wise or feature wise)
* standard format refers to data that has 0 mean and unit variance(i.e standard deviation=1),and the process of converting  data into this format is called data standardization